version: '3'
services:

  react-app:
    build: . 
    ports:
      - 3000:3000

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret
  
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongoadmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on: 
      - "mongodb"
  
  nginx-web:
    container_name: nginx-web
    image: openresty/openresty:buster-fat
    ports:
      - "80:80"
      # - "443:443"
    volumes:
      - "${NGINX_DIR}/conf:/usr/local/openresty/nginx/conf"
      - "${NGINX_DIR}/logs:/var/log/nginx/:rw" 
      - "${NGINX_DIR}/conf.d:/usr/local/openresty/nginx/conf/conf.d"
    environment:
      - TZ=Asia/Shanghai